<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsForFilm($filmId)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.film = :film_id')
                   ->addOrderBy('c.created')
                   ->setParameter('film_id', $filmId);

        

        return $qb->getQuery()
                  ->getResult();
    }
}
