frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

film_show:
    path:     /film/show/{id}
    defaults: { _controller: FrontendBundle:Default:show }

article_show:
    path:     /article
    defaults: { _controller: FrontendBundle:Default:article }

admin_film_new:
    path:     /admin/film/new
    defaults: { _controller: FrontendBundle:Default:newFilm }

comment_create:
    pattern:  /comment/{film_id}
    defaults: { _controller: FrontendBundle:Comment:create }
    requirements:
        _method:  POST
        film_id: \d+
